### ISSUE TITLE
'Added' class for seeds?

### ISSUE THREAD

**Issue by averyhadzi** [trebor/coral#4]
Can we add a class to items in the seed dropdown menus if/when they've been added to the ruleset?

**Comment by trebor** [comment]
yes we can.

this is my current plan for seed changing.

1. a user selects a seed (from the control panel or mobile device)
2. a message shows up on the control panel, saying that the new seed as been requested.
3. at that point changing the seed is temporarily  locked out.
4. the visualization continues on with it's current search terms (so there is no disruption of eye candy)
5. if enough tweets for the new seed are detected, the diagram cuts over to using the new seed.
6. if too few tweets are detected in some time range (like say 40 seconds) then a message saying that is displayed.

**Comment by averyhadzi** [comment]
Beautiful! 
I didn't realize that you can only change the seed via the dropdown(s)... for some reason I thought you could add multiple seeds from the menus. That certainly changes things on the css/icon side a bit! I'll make some tweaks and submit a PR.

**Comment by trebor** [comment]
i think this issue is covered by the current changes. re-open if not.
